import { Metadata } from 'next'
import ThemeController from '@/components/themeController'
import Link from 'next/link'
import Script from 'next/script'

export const metadata: Metadata = {
  title: 'Random Phone Numbers - Terms of Use',
  description: 'Terms of use for Random Phone Numbers. Understand our service terms and conditions when using our phone number generation tool.'
}

export default function TermsPage() {
  return (
    <main className="min-h-screen w-full relative bg-base-100">
      <ThemeController />
      
      {/* Header */}
      <section className="py-12 bg-base-200">
        <div className="container mx-auto px-4 text-center">
          <h1 className="text-4xl font-bold mb-4">Terms of Use</h1>
          <p className="text-xl text-base-content/80 max-w-2xl mx-auto">
            Please read these terms carefully before using our service
          </p>
        </div>
      </section>

      <section className="py-8">
        <div className="container mx-auto px-4">
          <div className="flex justify-center">
            <Script
              async
              data-cfasync="false"
              src="//pl26170375.effectiveratecpm.com/e600160624986baf8eabc5850c18a018/invoke.js"
              strategy="afterInteractive"
            />
            <div
              id="container-e600160624986baf8eabc5850c18a018"
              className="w-full"
            ></div>
          </div>
        </div>
      </section>
      
      {/* Content */}
      <div className="container mx-auto px-4 py-12">
        <div className="max-w-3xl mx-auto">
          <div className="bg-base-200 p-8 rounded-xl shadow-lg mb-8">
            <h2 className="text-2xl font-bold mb-6 text-primary">Terms of Service</h2>
            <p className="text-base-content/80 mb-4">
              By using this service, you agree to the following terms:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-base-content/80">
              <li>Generated phone numbers are for testing and development purposes only</li>
              <li>Numbers must not be used for fraud, harassment, spam, or any illegal purposes</li>
              <li>We provide no guarantee of number validity or availability</li>
              <li>Use of this service is at your own risk</li>
              <li>We reserve the right to limit or block access to users who violate these terms</li>
              <li>We may update these terms at any time without prior notice</li>
            </ul>
          </div>

          <div className="bg-base-200 p-8 rounded-xl shadow-lg mb-8">
            <h2 className="text-2xl font-bold mb-6 text-primary">Disclaimer</h2>
            <p className="text-base-content/80 mb-4">
              The phone numbers generated by this service are for testing purposes only. We are not responsible for:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-base-content/80">
              <li>Actual availability or ownership status of generated numbers</li>
              <li>Any losses, damages, or liabilities caused by using generated numbers</li>
              <li>Service interruptions, errors, or unavailability</li>
              <li>Accuracy of information provided about phone number formats</li>
              <li>Any consequences resulting from the use of our service</li>
            </ul>
          </div>

          <div className="bg-base-200 p-8 rounded-xl shadow-lg mb-8">
            <h2 className="text-2xl font-bold mb-6 text-primary">Intellectual Property</h2>
            <p className="text-base-content/80 mb-4">
              All content on this website, including but not limited to text, graphics, logos, and software, is the property of Random Phone Numbers and is protected by intellectual property laws.
            </p>
            <ul className="list-disc pl-6 space-y-2 text-base-content/80">
              <li>You may not reproduce, distribute, or create derivative works without our permission</li>
              <li>The service name, logo, and design elements are our trademarks</li>
              <li>You may use our service for its intended purpose only</li>
              <li>Scraping or automated access to our service is prohibited without prior written consent</li>
            </ul>
          </div>

          <div className="bg-base-200 p-8 rounded-xl shadow-lg mb-8">
            <h2 className="text-2xl font-bold mb-6 text-primary">Limitation of Liability</h2>
            <p className="text-base-content/80 mb-4">
              To the maximum extent permitted by law, we shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-base-content/80">
              <li>Your use or inability to use our service</li>
              <li>Any unauthorized access to or use of our servers</li>
              <li>Any interruption or cessation of transmission to or from our service</li>
              <li>Any bugs, viruses, or other harmful code that may be transmitted through our service</li>
            </ul>
          </div>

          <div className="bg-base-200 p-8 rounded-xl shadow-lg">
            <h2 className="text-2xl font-bold mb-6 text-primary">Governing Law</h2>
            <p className="text-base-content/80">
              These Terms shall be governed by and construed in accordance with the laws of the jurisdiction in which we operate, without regard to its conflict of law provisions. Any disputes relating to these terms shall be subject to the exclusive jurisdiction of the courts in that jurisdiction.
            </p>
          </div>
          
          <div className="mt-8 text-center">
            <Link 
              href="/" 
              className="inline-block px-6 py-3 bg-primary text-white rounded-lg hover:bg-primary/90 transition-colors duration-200"
            >
              Return to Home
            </Link>
          </div>
        </div>
      </div>
    </main>
  )
}