import { Metadata } from 'next'
import ThemeController from '@/components/themeController'

export const metadata: Metadata = {
  title: 'Terms of Use - Phone Number Generator',
  description: 'Terms of use for Phone Number Generator. Understand our service terms and conditions when using our phone number generation tool.',
  keywords: [
    'terms of use',
    'terms and conditions',
    'service terms',
    'usage terms',
    'phone number generator terms'
  ].join(', ')
}

export default function TermsPage() {
  return (
    <main className="min-h-screen w-full relative">
      <ThemeController />
      
      <div className="container mx-auto px-4 py-12 prose max-w-3xl">
        <h1>Terms of Use</h1>
        
        <section>
          <h2>Terms of Service</h2>
          <p>By using this service, you agree to the following terms:</p>
          <ul>
            <li>Generated numbers are for testing purposes only</li>
            <li>Must not be used for fraud or illegal purposes</li>
            <li>No guarantee of number validity</li>
            <li>Use of this service is at your own risk</li>
          </ul>
        </section>

        <section>
          <h2>Disclaimer</h2>
          <p>
            The phone numbers generated by this service are for testing purposes only. We are not responsible for:
          </p>
          <ul>
            <li>Actual availability of numbers</li>
            <li>Any losses caused by using generated numbers</li>
            <li>Service interruptions or unavailability</li>
          </ul>
        </section>
      </div>
    </main>
  )
} 